# Generated by Django 2.0.4 on 2018-05-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='emailID',
            new_name='email_ID',
        ),
    ]
