# Generated by Django 2.0.4 on 2018-05-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180530_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to='student.Instructor'),
        ),
    ]
