# Generated by Django 2.0.4 on 2018-05-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180530_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='rank_color',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Yellow Black', 'Yellow Black'), ('Green', 'Green'), ('Green Black', 'Green Black'), ('Purple', 'Purple'), ('Purple Black', 'Purple Black'), ('Orange', 'Orange'), ('Orange Black', 'Orange Black'), ('Blue', 'Blue'), ('Blue Black', 'Blue Black'), ('Brown', 'Brown'), ('Brown Black', 'Brown Black'), ('Red', 'Red'), ('Red Black', 'Red Black'), ('Black', 'Black')], max_length=20),
        ),
    ]
