# Generated by Django 2.0.4 on 2018-05-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180530_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='student.Transaction'),
        ),
    ]
