# Generated by Django 2.0.4 on 2018-05-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180530_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_month',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_year',
        ),
    ]
