# Generated by Django 2.0.4 on 2018-05-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180530_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='progress',
        ),
    ]
