# Generated by Django 2.0.4 on 2018-05-31 03:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180530_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=50)),
                ('fee_date', models.DateField(default=datetime.datetime(2018, 5, 31, 3, 55, 41, 480504, tzinfo=utc))),
                ('fee_amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fees',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fee',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='student.Student'),
        ),
    ]
