# Generated by Django 2.0.4 on 2018-05-31 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20180530_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
