# Generated by Django 2.0.4 on 2018-05-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20180530_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Rank'),
        ),
    ]
