# Generated by Django 2.0.6 on 2018-06-17 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20180531_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_month',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_year',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.CharField(default=datetime.datetime(2018, 6, 17, 10, 43, 51, 24427), max_length=20),
        ),
    ]
