# Generated by Django 2.0.6 on 2018-06-17 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180617_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.datetime(2018, 6, 17, 11, 20, 46, 825622), max_length=20),
        ),
    ]
