# Generated by Django 2.0.6 on 2018-06-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20180618_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_belt_from',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Rank'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_belt_to',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has', to='student.Rank'),
        ),
    ]
