# Generated by Django 2.0.6 on 2018-06-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20180619_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Rank'),
        ),
    ]
