# Generated by Django 2.0.6 on 2018-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20180619_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='postal_code',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='province',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='street_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='province',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='street_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='province',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='street_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
